import { Header } from '@/app/dashboard-menu/components/header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Page Design Gallery',
  description: 'Generated by dash board menu',
};

export default function DashboardMenuLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <main>{children}</main>
    </div>
  );
}
